/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.operaatio;
import java.awt.Color;
import java.awt.Graphics2D;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.undo.AbstractUndoableEdit;
import javax.swing.undo.UndoManager;
import model.Askartelu;
import model.Myynti;
import model.Tuote;

/**
 *
 * @author Joni
 */
public class kayttoliittyma extends javax.swing.JFrame {

    /**
     * Creates new form kayttoliittyma
     */
    public kayttoliittyma() {
        initComponents();
        kohdelappu.setVisible(false);
        hintalappu.setVisible(false);
        hiinta.setVisible(false);
        koohde.setVisible(false);
        hinta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tuotteenLisays = new javax.swing.JFrame();
        tuotteenNimi = new javax.swing.JTextField();
        Askartelu = new javax.swing.JRadioButton();
        Myynti = new javax.swing.JRadioButton();
        hyllyNumero = new javax.swing.JTextField();
        hyllyPaikka = new javax.swing.JTextField();
        hyllyKorkeus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lisaaTuote = new javax.swing.JButton();
        koohde = new javax.swing.JTextField();
        kohdelappu = new javax.swing.JLabel();
        hiinta = new javax.swing.JTextField();
        hintalappu = new javax.swing.JLabel();
        hinta = new javax.swing.JSlider();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        undo = new javax.swing.JMenuItem();
        redo = new javax.swing.JMenuItem();
        tuotteenHaku = new javax.swing.JFrame();
        hakuNimi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hakuId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hakuAskartelu = new javax.swing.JRadioButton();
        hakuMyynti = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tuoteEsitys = new javax.swing.JDialog();
        tuoteListaus = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuotelistaustila = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        tuotteenPoisto = new javax.swing.JFrame();
        idPoistoE = new javax.swing.JButton();
        idPoistoN = new javax.swing.JButton();
        idPoisto = new javax.swing.JTextField();
        piirto = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        idTaulu = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Esitys = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        lisays = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        tuotteenLisays.setSize(new java.awt.Dimension(800, 600));

        tuotteenNimi.setText("Anna tuotteen nimi");
        tuotteenNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuotteenNimiActionPerformed(evt);
            }
        });

        Askartelu.setText("Askartelu");
        Askartelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AskarteluActionPerformed(evt);
            }
        });

        Myynti.setText("Myyntituote");
        Myynti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyyntiActionPerformed(evt);
            }
        });

        hyllyNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyllyNumeroActionPerformed(evt);
            }
        });

        hyllyPaikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyllyPaikkaActionPerformed(evt);
            }
        });

        hyllyKorkeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyllyKorkeusActionPerformed(evt);
            }
        });

        jLabel1.setText("Hylly");

        jLabel2.setText("paikka");

        jLabel3.setText("taso (1-3)");

        lisaaTuote.setText("Lisää");
        lisaaTuote.setEnabled(false);
        lisaaTuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTuoteActionPerformed(evt);
            }
        });

        koohde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                koohdePropertyChange(evt);
            }
        });

        kohdelappu.setText("Kohde");

        hiinta.setText("0");
        hiinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiintaActionPerformed(evt);
            }
        });

        hintalappu.setText("Hinta");

        hinta.setMaximum(150);
        hinta.setValue(0);
        hinta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hintaStateChanged(evt);
            }
        });

        jMenu6.setText("Edit");

        undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undo.setText("undo");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jMenu6.add(undo);

        redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redo.setText("redo");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        jMenu6.add(redo);

        jMenuBar3.add(jMenu6);

        tuotteenLisays.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout tuotteenLisaysLayout = new javax.swing.GroupLayout(tuotteenLisays.getContentPane());
        tuotteenLisays.getContentPane().setLayout(tuotteenLisaysLayout);
        tuotteenLisaysLayout.setHorizontalGroup(
            tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuotteenLisaysLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lisaaTuote))
                    .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                        .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuotteenNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Askartelu)
                                    .addComponent(Myynti)
                                    .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                                        .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hyllyKorkeus, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                            .addComponent(hyllyPaikka)
                                            .addComponent(hyllyNumero))
                                        .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuotteenLisaysLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel2)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuotteenLisaysLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel3)))))
                                .addGap(126, 126, 126)
                                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                                        .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                                                .addComponent(hiinta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hintalappu))
                                            .addComponent(koohde, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kohdelappu)))))
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tuotteenLisaysLayout.setVerticalGroup(
            tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuotteenLisaysLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tuotteenNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Askartelu)
                    .addComponent(koohde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kohdelappu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Myynti)
                    .addComponent(hiinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintalappu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hyllyNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(hinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hyllyPaikka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(tuotteenLisaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hyllyKorkeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(lisaaTuote)
                .addGap(72, 72, 72))
        );

        tuotteenHaku.setSize(new java.awt.Dimension(800, 600));

        jLabel4.setText("Tuotteen nimi");

        jLabel5.setText("Tuotteen id");

        hakuAskartelu.setText("askartelu");
        hakuAskartelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakuAskarteluActionPerformed(evt);
            }
        });

        hakuMyynti.setText("Myynti");
        hakuMyynti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakuMyyntiActionPerformed(evt);
            }
        });

        jButton2.setText("Hae");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("peruuta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tuotteenHakuLayout = new javax.swing.GroupLayout(tuotteenHaku.getContentPane());
        tuotteenHaku.getContentPane().setLayout(tuotteenHakuLayout);
        tuotteenHakuLayout.setHorizontalGroup(
            tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuotteenHakuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tuotteenHakuLayout.createSequentialGroup()
                        .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tuotteenHakuLayout.createSequentialGroup()
                                .addComponent(hakuAskartelu)
                                .addGap(51, 51, 51)
                                .addComponent(hakuMyynti))
                            .addGroup(tuotteenHakuLayout.createSequentialGroup()
                                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hakuNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hakuId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(0, 704, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuotteenHakuLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        tuotteenHakuLayout.setVerticalGroup(
            tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuotteenHakuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hakuNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hakuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hakuAskartelu)
                    .addComponent(hakuMyynti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1186, Short.MAX_VALUE)
                .addGroup(tuotteenHakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout tuoteEsitysLayout = new javax.swing.GroupLayout(tuoteEsitys.getContentPane());
        tuoteEsitys.getContentPane().setLayout(tuoteEsitysLayout);
        tuoteEsitysLayout.setHorizontalGroup(
            tuoteEsitysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        tuoteEsitysLayout.setVerticalGroup(
            tuoteEsitysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        tuoteListaus.setSize(new java.awt.Dimension(800, 600));

        tuotelistaustila.setColumns(20);
        tuotelistaustila.setRows(5);
        jScrollPane1.setViewportView(tuotelistaustila);

        javax.swing.GroupLayout tuoteListausLayout = new javax.swing.GroupLayout(tuoteListaus.getContentPane());
        tuoteListaus.getContentPane().setLayout(tuoteListausLayout);
        tuoteListausLayout.setHorizontalGroup(
            tuoteListausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuoteListausLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        tuoteListausLayout.setVerticalGroup(
            tuoteListausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuoteListausLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        tuotteenPoisto.setSize(new java.awt.Dimension(800, 600));

        idPoistoE.setText("Exit");

        idPoistoN.setText("Poista");
        idPoistoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPoistoNActionPerformed(evt);
            }
        });

        idPoisto.setText("Anna tuotteen ID");

        javax.swing.GroupLayout tuotteenPoistoLayout = new javax.swing.GroupLayout(tuotteenPoisto.getContentPane());
        tuotteenPoisto.getContentPane().setLayout(tuotteenPoistoLayout);
        tuotteenPoistoLayout.setHorizontalGroup(
            tuotteenPoistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuotteenPoistoLayout.createSequentialGroup()
                .addComponent(idPoistoE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tuotteenPoistoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPoisto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(idPoistoN)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        tuotteenPoistoLayout.setVerticalGroup(
            tuotteenPoistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tuotteenPoistoLayout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(tuotteenPoistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPoisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPoistoN))
                .addGap(111, 111, 111)
                .addComponent(idPoistoE)
                .addContainerGap())
        );

        piirto.setSize(new java.awt.Dimension(300, 200));

        idTaulu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tuotteen ID"
            }
        ));
        jScrollPane2.setViewportView(idTaulu);

        jButton5.setText("Näyt tuotteet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("lisää rivejä");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        piirto.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout piirtoLayout = new javax.swing.GroupLayout(piirto.getContentPane());
        piirto.getContentPane().setLayout(piirtoLayout);
        piirtoLayout.setHorizontalGroup(
            piirtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piirtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(piirtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        piirtoLayout.setVerticalGroup(
            piirtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piirtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piirtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piirtoLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(42, 42, 42)
                        .addComponent(jButton5)
                        .addGap(0, 192, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        Esitys.setSize(new java.awt.Dimension(900, 600));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/kuvat/varastoPohja.png"))); // NOI18N

        javax.swing.GroupLayout EsitysLayout = new javax.swing.GroupLayout(Esitys.getContentPane());
        Esitys.getContentPane().setLayout(EsitysLayout);
        EsitysLayout.setHorizontalGroup(
            EsitysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EsitysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EsitysLayout.setVerticalGroup(
            EsitysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EsitysLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 149, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        lisays.setText("Lisaa tuote");
        lisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaysActionPerformed(evt);
            }
        });
        lisays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lisaysKeyPressed(evt);
            }
        });

        jButton1.setText("Hae tuote");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Poista tuote");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Hae kartasta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Näytä pohja");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });

        jMenu1.setText("File");

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lisays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton8)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lisays)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(52, 52, 52)
                .addComponent(jButton8)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void lisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaysActionPerformed
        tuotteenLisays.setVisible(true);        //tuotteen lisaaminen

    }//GEN-LAST:event_lisaysActionPerformed

    private void tuotteenNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuotteenNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuotteenNimiActionPerformed

    private void AskarteluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AskarteluActionPerformed
        Myynti.setSelected(false);
        lisaaTuote.setEnabled(true);
        koohde.setVisible(true);
        kohdelappu.setVisible(true);
        hiinta.setVisible(false);
        hinta.setVisible(false);
        hintalappu.setVisible(false);
    }//GEN-LAST:event_AskarteluActionPerformed

    private void MyyntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyyntiActionPerformed
        Askartelu.setSelected(false);
        lisaaTuote.setEnabled(true);
        koohde.setVisible(false);
        kohdelappu.setVisible(false);
        hiinta.setVisible(true);
        hinta.setVisible(true);       
        hintalappu.setVisible(true);
    }//GEN-LAST:event_MyyntiActionPerformed

    private void hyllyNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyllyNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyllyNumeroActionPerformed

    private void hyllyPaikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyllyPaikkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyllyPaikkaActionPerformed

    private void hyllyKorkeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyllyKorkeusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyllyKorkeusActionPerformed

    private void lisaaTuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTuoteActionPerformed
        //jos käyttäjä haluaa luoda tuotteen, on toisen valinnoista oltava valittuna
        int tmpHylly = Integer.parseInt(hyllyNumero.getText());
        int tmpPaikka = Integer.parseInt(hyllyPaikka.getText());
        int tmpKorkeus = Integer.parseInt(hyllyKorkeus.getText());
        String tmpNimi = tuotteenNimi.getText();
        String kohde = koohde.getText();
        double arvo = Double.parseDouble(hiinta.getText());
        boolean ok = false;
        int id = ajo.idpalautus();

        //jos tuote on askartelutuote
        if (Askartelu.isSelected() == true) {
            if (koohde.getText().equals("") || koohde.getText().equals("ANNA KOHDE")) {
                koohde.setText("ANNA KOHDE");
                ok = false;
            } else {
                ok = true;
            }
            //jos askartelulle on annettu kohde luodaan uusi tuote
            if (ok == true) {
                Askartelu a = new Askartelu(tmpHylly, tmpPaikka, tmpKorkeus, id, kohde, tmpNimi);
                ajo.lisaaTuote(a);
                tuotteenLisays.setVisible(false);
            }
        } //jos kyseessä myytävä tuote
        else {
            Myynti b = new Myynti(tmpHylly, tmpPaikka, tmpKorkeus, id, arvo, tmpNimi);
            ajo.lisaaTuote(b);
            tuotteenLisays.setVisible(false);
        }
        
    }//GEN-LAST:event_lisaaTuoteActionPerformed

    private void hiintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiintaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tuotteenHaku.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //jos mitään hakutietoa ei ole annettu, pyydetään käyttäjää antamaan tieto
        LinkedList tempo = new LinkedList();
        LinkedList temporal = new LinkedList();
        boolean lopeta = false;
        if ("".equals(hakuId.getText()) && hakuAskartelu.isSelected() == false
                && hakuMyynti.isSelected() == false && "".equals(hakuNimi.getText())) {
            JOptionPane.showMessageDialog(null, "Anna jokin hakukriteeri");
        }
        //jos on annettu id haetaan sillä
        if (!"".equals(hakuId.getText())) {
            Tuote tmp = (Tuote) ajo.palautaId(Integer.parseInt(hakuId.getText()));
            if (tmp != null) {
                JOptionPane.showMessageDialog(null, tmp);
                lopeta = true;
            } else {
                JOptionPane.showMessageDialog(null, "id:llä: " + hakuId.getText() + "   ei löytynyt tuotteita");
            }
        } //jos id ei oltu annettu
        else if (lopeta == false) {
            //jos id ei ole annettu, tarkastetaan onko askartelu/myynti valittu
            if (hakuAskartelu.isSelected() == true) {
                tempo = ajo.getAskarteluLista();
            } else if (hakuMyynti.isSelected() == true) {
                tempo = ajo.getMyyntiLista();
            } else {
                tempo = ajo.getTuoteLista();
            }
            //jos tuotteelle ei ole annettu nimeä, haetaan kaikki tuotetiedot
            if ("".equals(hakuNimi.getText())) {
                tuoteListaus.setVisible(true);
                tuotelistaustila.setText("");
                for (int i = 0; i < tempo.size(); i++) {
                    String tm = tuotelistaustila.getText();
                    tuotelistaustila.setText(tm + '\n' + tempo.get(i));
                    lopeta = true;
                }
            } //jos nimi on annettu, haetaan sillä
            else if (!"".equals(hakuNimi.getText())) {
                String haku = hakuNimi.getText();
                for (int i = 0; i < tempo.size(); i++) {
                    if (ajo.palautaNimella((Tuote) tempo.get(i), haku) == true) {
                        temporal.add(tempo.get(i));

                        lopeta = true;
                    }
                }
                if (temporal.size() >= 1) {
                    tuoteListaus.setVisible(true);
                }
                for (int i = 0; i < temporal.size(); i++) {
                    String tm = tuotelistaustila.getText();
                    tuotelistaustila.setText(tm + '\n' + temporal.get(i));
                    lopeta = true;
                }
            }
        }

        if (lopeta == true) {
            tuotteenHaku.dispose();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tuotteenHaku.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hakuAskarteluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakuAskarteluActionPerformed
        hakuMyynti.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_hakuAskarteluActionPerformed

    private void hakuMyyntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakuMyyntiActionPerformed
        hakuAskartelu.setSelected(false);    // TODO add your handling code here:
    }//GEN-LAST:event_hakuMyyntiActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        jf.setFileFilter(filter);
        int returnVal = jf.showSaveDialog(this);
        if (returnVal == jf.APPROVE_OPTION) {
            File file = jf.getSelectedFile();
            try (PrintWriter writer = new PrintWriter(file, "UTF-8")) {
                LinkedList temp = ajo.getTuoteLista();

                for (int i = 0; i < temp.size(); i++) {
                    writer.println(temp.get(i));
                }   //suljetaan kirjoitin.
                writer.close();        // TODO add your handling code here:
            } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                Logger.getLogger(kayttoliittyma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
                        LinkedList<Tuote> tmpTuote = new LinkedList();
                LinkedList<Askartelu> tmpAsk = new LinkedList();
                LinkedList<Myynti> tmpMyynt = new LinkedList();
        Scanner lukija = new Scanner("");
        try {

            // Laitetaan oliot ensin valiaikaiseen listaan,
            // jotta voidaan varmistua etta koko operaatio joko onnistuu tai epaonnistuu
            JFileChooser jf = new JFileChooser();
            int returnVal = jf.showOpenDialog(this);
        if (returnVal == jf.APPROVE_OPTION) {
            File file = jf.getSelectedFile();            
            lukija = new Scanner(file);
        }


            // otetaan talteen siemenLuku, maxX ja maxY arvot loopin ulkopuolella tiedostosta
                       
            while (lukija.hasNextLine()) {
                String rivi = lukija.nextLine();
                String[] osat = rivi.split("[|]");

                // Poistetaan turhat valilyonnit
                for (int i = 0; i < osat.length; i++) {
                    osat[i] = osat[i].trim();
                }
                String nimi = osat[0];
                int id = Character.getNumericValue(osat[1].charAt(4));
                int hylly = Character.getNumericValue(osat[2].charAt(7));
                int paikka = Character.getNumericValue(osat[3].charAt(8));
                int Korkeus = Character.getNumericValue(osat[4].charAt(9));
                String muu = osat[5];
                        
                //jos kyseessä myytävä tuote (eli MUU voidaan muuntaa doubleksi)
                try {
                  double arvo =  Double.parseDouble(muu);

                Myynti b = new Myynti(hylly, paikka, Korkeus, id, arvo, nimi);
                tmpTuote.add(b);
                tmpMyynt.add(b);
                    
                }
                catch (Exception e)
                {
                Askartelu a = new Askartelu(hylly, paikka, Korkeus, id, muu, nimi);
                tmpTuote.add(a);
                tmpAsk.add(a);
                }
            }
            //jos tuotteita on saatu ladattu
            if (tmpAsk.size()>0 || tmpMyynt.size()>0)
            {
                            ajo.setAskarteluLista(tmpAsk);
            ajo.setMyyntiLista(tmpMyynt);
            ajo.setTuoteLista(tmpTuote);
            }

            
        } 
        catch (IOException e) {
            // Jos tiedostoa ei loydy, otetaan errori talteen ja palautetaan virheilmoitus kayttajalle
            System.out.println("Tiedostoa ei loytynyt");
        }
        finally {
            lukija.close();
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tuotteenPoisto.setVisible(true);                // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idPoistoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPoistoNActionPerformed
        try {

            int tarkastettava = Integer.parseInt(idPoisto.getText());
            if (tarkastettava < 1) {

                JOptionPane.showMessageDialog(null, "Tuotteet on numeroitu juoksevasti 1 alkaen");
            } else {
                boolean tmp = ajo.poistaTuote(tarkastettava);
                System.out.println(tmp);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syötä ID lukuna");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_idPoistoNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        for (int i = 0; i < idTaulu.getRowCount(); i++) {
            for (int j = 0; j < idTaulu.getColumnCount(); j++) {
                idTaulu.setValueAt("", i, j);
            }
        }
        piirto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            LinkedList<Tuote> a = new LinkedList();
            idTaulu.getCellEditor().stopCellEditing();
            for (int i = 0; i < idTaulu.getRowCount(); i++) {
                System.out.println(i + " " + idTaulu.getValueAt(i, 0));
                String tm = (String) idTaulu.getValueAt(i, 0);
                Tuote t = ajo.palautaTuote(Integer.parseInt(tm));
                if (t != null) {
                    a.add(t);
                }
            }
            Karttakuva tmp = new Karttakuva(a);
            tmp.setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "syota ID numerona");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Ala jata tyhjia riveja");
        }

        //
        //tmp.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Esitys.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel model = (DefaultTableModel) idTaulu.getModel();
        model.addRow(new Object[]{"", ""});        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        if (undos.canUndo()) {
            undos.undo();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_undoActionPerformed

    private void koohdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_koohdePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_koohdePropertyChange

    private void hintaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hintaStateChanged
               
        if (!hinta.getValueIsAdjusting()) {
            // talletetaan uusi ja vanha
            String oldValue = hiinta.getText();
            String newValue = "" + hinta.getValue();
        
            if (oldValue.equals(newValue)) {
                return;
            }
         
            undos.addEdit(new AbstractUndoableEdit() {
                @Override
                public void undo() {
                    super.undo();
                    hiinta.setText(oldValue);
                   
                    try {
                        hinta.setValue(Integer.parseInt(oldValue));
                    } catch (NumberFormatException e) {
                    }
               
                    updateUndoElements();
                }
                
                public void redo() {
                    super.redo();
                  
                    hiinta.setText(newValue);
                    try {
                        hinta.setValue(Integer.parseInt(newValue));
                    } catch (NumberFormatException e) {
                    }
                    updateUndoElements();
                    
                }

                public String getPresentationName() {
                    return "Slider Change";
                }
            });

            hiinta.setText("" + hinta.getValue());
            updateUndoElements();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_hintaStateChanged

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        if (undos.canRedo())
            undos.redo();        // TODO add your handling code here:
    }//GEN-LAST:event_redoActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void lisaysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lisaysKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lisaysKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
                // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
        jButton8.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "jBut");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8KeyPressed
    void updateUndoElements() {
        // Menu text can be queried from UndoManager which gets them 
        // from undoable edits.
        undo.setText(undos.getUndoPresentationName());
        redo.setText(undos.getRedoPresentationName());
        undo.setEnabled(undos.canUndo());
        redo.setEnabled(undos.canRedo());
    }
    /**
     * @param args the command line arguments
     */
    operaatio ajo = new operaatio();

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayttoliittyma().setVisible(true);

            }
        });
    }
    UndoManager undos = new UndoManager();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Askartelu;
    private javax.swing.JFrame Esitys;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JRadioButton Myynti;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JRadioButton hakuAskartelu;
    private javax.swing.JTextField hakuId;
    private javax.swing.JRadioButton hakuMyynti;
    private javax.swing.JTextField hakuNimi;
    private javax.swing.JTextField hiinta;
    private javax.swing.JSlider hinta;
    private javax.swing.JLabel hintalappu;
    private javax.swing.JTextField hyllyKorkeus;
    private javax.swing.JTextField hyllyNumero;
    private javax.swing.JTextField hyllyPaikka;
    private javax.swing.JTextField idPoisto;
    private javax.swing.JButton idPoistoE;
    private javax.swing.JButton idPoistoN;
    private javax.swing.JTable idTaulu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kohdelappu;
    private javax.swing.JTextField koohde;
    private javax.swing.JButton lisaaTuote;
    private javax.swing.JButton lisays;
    private javax.swing.JFrame piirto;
    private javax.swing.JMenuItem redo;
    private javax.swing.JDialog tuoteEsitys;
    private javax.swing.JFrame tuoteListaus;
    private javax.swing.JTextArea tuotelistaustila;
    private javax.swing.JFrame tuotteenHaku;
    private javax.swing.JFrame tuotteenLisays;
    private javax.swing.JTextField tuotteenNimi;
    private javax.swing.JFrame tuotteenPoisto;
    private javax.swing.JMenuItem undo;
    // End of variables declaration//GEN-END:variables
}
